namespace Eye.CombatLog.Core
{
    public enum CombatLogEntryTypes
    {
        Invalid = -1,
        Damage = 0,
        Heal = 1,
        ModifierAdd = 2,
        ModifierRemove = 3,
        Death = 4,
        Ability = 5,
        Item = 6,
        Location = 7,
        Gold = 8,
        GameState = 9,
        Xp = 10,
        Purchase = 11,
        Buyback = 12,
        AbilityTrigger = 13,
        Playerstats = 14,
        Multikill = 15,
        Killstreak = 16,
        TeamBuildingKill = 17,
        FirstBlood = 18,
        ModifierStackEvent = 19,
        NeutralCampStack = 20,
        PickupRune = 21,
        RevealedInvisible = 22,
        HeroSaved = 23,
        ManaRestored = 24,
        HeroLevelup = 25,
        BottleHealAlly = 26,
        EndgameStats = 27,
        InterruptChannel = 28,
        AlliedGold = 29,
        AegisTaken = 30,
        ManaDamage = 31,
        PhysicalDamagePrevented = 32,
        UnitSummoned = 33,
        AttackEvade = 34,
        TreeCut = 35,
        SuccessfulScan = 36,
        EndKillstreak = 37,
        BloodstoneCharge = 38,
        CriticalDamage = 39,
        SpellAbsorb = 40,
        UnitTeleported = 41,
        KillEaterEvent = 42
    }
}